### ISSUE TITLE
Allow meta data extraction for files from non-local storages

### ISSUE THREAD

**Issue by IchHabRecht** [TYPO3-Solr/ext-tika#122]
Currently there is a limitation to files from file storages using the local driver only. Is this an intended (necessary) limitation of tike? I haven't found any documentation about that. And I cannot see any reason why other drivers / storages using other drivers should be excluded. As you already mention in your documentation, tika is using the FAL api. So in my point of view this should not be related to any driver of the storage.

**Comment by dkd-dobberkau** [comment]
Hi Nicole.
There is no intention to limit the usage. We simply don't encounter in our use cases the integration of other FAL storages for the moment.

**Comment by IchHabRecht** [comment]
Thank for taking care of the rebase!
