### ISSUE TITLE
[BUG] use ExtensionConfiguration Api to Access Configuration

### ISSUE THREAD

**Issue by achimfritz** [TYPO3-Solr/ext-tika#129]
currently Extension Configuration is fetch by 
`$tikaConfiguration = unserialize($GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf']['tika']);`

This must be changed to
`\TYPO3\CMS\Core\Configuration\ExtensionConfiguration->get('tika');`

see Core Deprecation Log
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.0/Deprecation-82254-DeprecateGLOBALSTYPO3_CONF_VARSEXTextConf.html

**Comment by dkd-kaehm** [comment]
Fixed: in #131
