### ISSUE TITLE
Update to Version 6.0 like stated in "solr" Version Matrix

### ISSUE THREAD

**Issue by hoermannklaus** [TYPO3-Solr/ext-tika#132]
I read in the [Version Matrix](https://docs.typo3.org/p/apache-solr-for-typo3/solr/11.0/en-us/Appendix/VersionMatrix.html) that "solr" 11 would be compatible with "tika" Version 6.0.0. 

Will there be a "tika" Version 6.0.0 any time soon?

Thanks

**Comment by dkd-dobberkau** [comment]
Soon. Hopefully in May.

**Comment by hoermannklaus** [comment]
Great. Looking forward to that. Thanks.
