### ISSUE TITLE
[TASK] Handle warnings in log

### ISSUE THREAD

**Issue by 3l73** [TYPO3-Solr/ext-tika#149]
During a check of log issues, I found following warnings from extension tika:

```
PHP Warning: Invalid argument supplied for foreach() in
typo3conf/ext/tika/Classes/Service/Tika/ServerService.php line 376
```

```
PHP Warning: get_object_vars() expects parameter 1 to be object, null given
in typo3conf/ext/tika/Classes/Service/Tika/ServerService.php line 373
```

These warnings should be checked and if required lead to an error or the code needs adjustments in order to reduce warnings.

**Comment by dkd-kaehm** [comment]
Backports for TYPO3 versions 9.5 + 10.4 required.
