### ISSUE TITLE
[TASK] Check and adjust log levels

### ISSUE THREAD

**Issue by dkd-friedrich** [TYPO3-Solr/ext-tika#160]
**What should be done in the scope of this task?**

Currently our log level usage seems to be messed up, e.g. we log the executed language detection with log level `0` (= emergency), but the message was of course only meant as a hint.

We should check and adjust the used log levels.

**Comment by 3l73** [comment]
Their is a relation with #137

**Comment by dkd-friedrich** [comment]
Fixed in #161
