### ISSUE TITLE
Epic [TASK] Make EXT:tika TYPO3 12 LTS compatible

### ISSUE THREAD

**Issue by 3l73** [TYPO3-Solr/ext-tika#198]
This task contains all the sub task to get EXT:tika woking within TYPO3 12 LTS:
**Note:** The compatibility to TYPO3 11 LTS MUST NOT be assured.

### TODO

- [ ] Example

**Comment by RZivaralam** [comment]
I would like to know when this plugin will be compatible with Typo 3 version 12?
