### ISSUE TITLE
[BUG] Error when extracting meta data with solr cell

### ISSUE THREAD

**Issue by timohund** [TYPO3-Solr/ext-tika#33]
When the metadata is extracted with solr cell there is an error when the scheduler task is executed. We should debug this.

**Comment by dkd-friedrich** [comment]
The Solr Cell service (`ApacheSolrForTypo3\Tika\Service\Tika\SolrCellService`) doesn't support language detection and throws an exception: `The Tika Solr service does not support language detection`

I think we should skip the language detector registration if EXT:tika is configured to use the Solr server.

**Comment by pniederlag** [comment]
Is there a fix in the pipe? 

We currently just patched the canProcess() in the LanguageDetector to return a hardcoded false. 

Otherwise tika ist just broken when used with solrServer :(

**Comment by timohund** [comment]
@pniederlag can you maybe create a pull request?

**Comment by timohund** [comment]
This is fixed by #41. Please open a new issue when there is still a problem.
