### ISSUE TITLE
Need for protocol and ignore of port number

### ISSUE THREAD

**Issue by thomashohn** [TYPO3-Solr/ext-tika#38]
We are about to go in production with the ext-tika extensions. But we have 2 major problems.

1. It should be possible to provide the protocol for the tika server - since we run https on all our systems.
2. If the port number is empty the extensions should not add a : to the connect string since this won't work.

It  would be nice to have these 2 fixed ASAP - alternatively we could provide a pull request for it.

**Comment by dkd-friedrich** [comment]
Hi Thomas! If you've the time to create a pull request, it would be great. As you might have heard already, Timo is on honeymoon currently and I'm not sure if Ingo or I can implement this in time.

**Comment by thomashohn** [comment]
So I have created a pull request - would be nice if you could merge it into the master branch :-)

**Comment by thomashohn** [comment]
The requested backwards compability has also been added - would be nice with a merge and a release :)
