### ISSUE TITLE
Check for valid configuration

### ISSUE THREAD

**Issue by irnnr** [TYPO3-Solr/ext-tika#4]
EXT:tika 2.0 won't use the old service APIs anymore. Those checked whether a service is available. As checking that would have been costly for Tika by starting the JVM each time we stored the results of a check in the TYPO3 registry.

We won't store the availability check results anymore and will instead assume the configuration to be valid.

However, we should add checks for valid configuration to the Status Report.

**Comment by timoschmidt** [comment]
Was done with #8

**Comment by irnnr** [comment]
I believe so, too. Let me double check tonight.

**Comment by irnnr** [comment]
just checked, not solved yet
