### ISSUE TITLE
ping function missing in SolrCellService

### ISSUE THREAD

**Issue by peterkraume** [TYPO3-Solr/ext-tika#5]
```
Fatal error: Call to undefined method ApacheSolrForTypo3\Tika\Service\Tika\SolrCellService::ping() in /..../typo3conf/ext/tika/Classes/Backend/SolrModule/TikaControlPanelModuleController.php on line 242
```

How to reproduce:
* latest git master from solr and tika
* Backend Module "search" => click on "Tika"

**Comment by timoschmidt** [comment]
Hi Peter, thanks for your report. I'll check this and come back to you when there is something new. When you have time to investigate this issue further this would also be nice.

**Comment by MoppieMop** [comment]
I have almost the same issue:
```PHP Fatal error:  Call to undefined method ApacheSolrForTypo3\\Tika\\Service\\Tika\\AppService::ping() in .../www/typo3conf/ext/tika/Classes/Backend/SolrModule/TikaControlPanelModuleController.php on line 242,```

**Comment by peterkraume** [comment]
@timoschmidt would be nice to have this fixed ASAP. Seems like the ping method was only implemented in Classes/Service/Tika/ServerService.php.

**Comment by timoschmidt** [comment]
@peterkraume 
@MoppieMop 

I've checked the issue and for me it looks like, that the backend module is not yet completly done. I've created a branch and a pull request with a fix, that the backend module is usable for all service types again.

Can you maybe please check the branch on your instllation and confirm, when it is working as before?

**Comment by MoppieMop** [comment]
I tested the PR and it seems to work - but I never had a "before" it is my first usage of ext-tika.
Is it correct that it says "Tika Mode: Jar". I would expect "Tikas Mode: App" or "Tika Mode: Server"

**Comment by timoschmidt** [comment]
Thx for this hint, i'll change this and merge the pull request afterwards

**Comment by timoschmidt** [comment]
I've merged the issue, thx for the report. When something is left, please re-open the issue.

**Comment by peterkraume** [comment]
Thx for the patch @timoschmidt! I've just tested it and it seems to work smoothly now.

**Comment by irnnr** [comment]
Sorry to step in here so late. However, I'm going to revert most of this change as the Tika backend module simply is/was not at a point yet where it was meant for use. At that point it was still experimental and explicitly was not meant to support anything but the Tika server. 

So when you configured the extension to use the Tika app or Solr it was logically failing.

The whole backend module is an idea I was playing with. Potentially not meant for release as it was (and still is!) unclear what it should do. At that point I was experimenting with allowing users to start and stop Tika from the TYPO3 backend. Again, that's something that only works for the server obviously.

**Comment by irnnr** [comment]
Apologizes if that caused any inconvenience and for not being clear about what the module should do.

**Comment by irnnr** [comment]
I now added a big red warning and a check for which extractor is being used so that the ping is only executed when the extension is configured to use Tika server. This way you won't run into the fatal error anymore.
