### ISSUE TITLE
[FEATURE] Make the Java VM MaxHeapSize configurable, to avoid the Java VM error "Could not reserve enough space for object heap"

### ISSUE THREAD

**Issue by LeoniePhiline** [TYPO3-Solr/ext-tika#55]
I use the tika app for heavy extraction work on a website full of media files. 

Here, I had to add another memory-expanding argument to the tika app command: 

`-Xmx512M`

(verbose version: `-XX:MaxHeapSize=512m`)

This prevents the Java VM error "Could not reserve enough space for object heap".

The tika EXTCONF could offer options like 256m, 512m etc., which would then be applied to the tika app java shell calls.

Thanks for your continued work!

**Comment by dkd-kaehm** [comment]
relates to #14, if it will be decided to drop Tika-"App"  support.

**Comment by dkd-kaehm** [comment]
Fixed in #172
