### ISSUE TITLE
[BUG]  file_get_contents() Warning under CMS 8 LTS

### ISSUE THREAD

**Issue by dkd-kaehm** [TYPO3-Solr/ext-tika#65]
Under CMS 8 LTS we get a warning in Backend:

```
Core: Error handler (BE): PHP Warning: file_get_contents(http://localhost:9999/tika): failed to open stream: Connection refused in /var/www/8.7.local.typo3.org/typo3conf/ext/tika/Classes/Service/Tika/ServerService.php line 242
```

**Comment by sascha-egerer** [comment]
There is no server on that host / port. Do you use a docker setup? Is that machine really running on port 9999 even in the internal network?

**Comment by dkd-kaehm** [comment]
@sascha-egerer, thanks for response. 
This Warning should not be shown in backend as message.
![Warning in Backend!](https://cloud.githubusercontent.com/assets/25453927/26820662/dc408ed2-4aa3-11e7-8b78-2885de32df22.png)

**Comment by dkd-kaehm** [comment]
Solved in previous versions.
