### ISSUE TITLE
[BUG] on Apache Solr 6.6 the QUERYHANDLER changed to QUERY

### ISSUE THREAD

**Issue by dkd-kaehm** [TYPO3-Solr/ext-tika#80]
on Apache Solr(Version 6.6!) mode the Reports module does not show the right status.

![bildschirmfoto 2017-11-07 um 14 11 09](https://user-images.githubusercontent.com/25453927/32495336-98a91b08-c3c5-11e7-81fc-32d6e0c905f3.JPG)
 
We need to make Tika compatible with Apache Solr 6.6

https://github.com/TYPO3-Solr/ext-tika/blob/release-2.3.x/Classes/Report/TikaStatus.php#L184-L187

can be solved as follows:

```
            if (array_key_exists('/update/extract', $plugins->plugins->QUERYHANDLER) 
                || array_key_exists('/update/extract', $plugins->plugins->QUERY)) {
                $solrCellConfigurationOk = true;
            }
```

**Comment by dkd-friedrich** [comment]
IMHO only EXT:tika 2.3.x is affected, alternatively to adapting the plugin request, a backport of #56 should help. 

A backport should fix this issue and additionally solve the issue with extract handlers lazy loading, we should check if a backport is possible and sufficient.

**Comment by dkd-kaehm** [comment]
Current versions in Solr Cell mode work properly.
EXT:tika 2.3.x is not supported any more.
