### ISSUE TITLE
Tika extracts and saves wrong width/height metadata of jpegs (EXIF)

### ISSUE THREAD

**Issue by rialDave** [TYPO3-Solr/ext-tika#84]
Hi,

as we can now reproduce, ext-tika seems to save wrong height and width metadata of jpeg (and maybe other) files.

**Main problem/symptom - for example:**
when a file is cropped or scaled down before uploading (e.g. photoshop) there will still be the initial width and height values in the metadata of this file along with the new and correct values (correlates with the EXIF data of the file).
Now after the upload process (with the tika extension installed) the initial values will be saved in the TYPO3 database (sys_file_metadata) instead of the new and correct values.
If you now want to crop the image with the TYPO3 cropping tool out of the core, it will save wrong cropping areas because of these values in sys_file_metadata.

**Steps to reproduce:**
1. Edit a .jpeg file with a image manipulation program like Photoshop and scale it down to a reduced resolution. 
2. Upload the edited file via the normal TYPO3 upload in BE while the tika ext is installed and active.
3. check the values of "height" and "width" for this file in the sys_file_metadata table. Those should now be the wrong values.

**Counter check:**
- If you upload the previously edited file via FTP/SFTP into your fileadmin and get it indexed by TYPO3 via opening the file module (so not uploading it via the BE) the values are stored correctly.
- If you deactivate the tika extension and proceed exactly like the reproduction steps above the values are stored correctly too.

If you need any further information, don't hesitate to hit me up.

**Comment by jackd248** [comment]
Got the same problem here, the wrong width/height are stored as metadata. It seems that ext-tika intervene in the upload process to read the _ImageWidth_ (original width/wrong value) instead of the _ExifImageWidth_ (resized width/correct value) of the EXIF data. 

Any updates to this issue?

**Comment by RostyslavMatviyiv** [comment]
Yes, the same issue on TYPO3 v8.7.27 and ext:tika v3.1.1. As I see tika wrongly takes "ImageWidth" and "ImageHeight" from EXIF data, instead of 

ExifImageWidth | 1024
-- | --
ExifImageHeight | 683

![image](https://user-images.githubusercontent.com/50489886/61693933-1a730f00-ad39-11e9-9f6b-0b9afe835f52.png)
![image](https://user-images.githubusercontent.com/50489886/61693944-1fd05980-ad39-11e9-9aca-43daf13c713b.png)

/typo3conf/ext/tika/Classes/Service/Extractor/MetaDataExtractor.php:
![image](https://user-images.githubusercontent.com/50489886/61693971-2e1e7580-ad39-11e9-8126-436258cc9ae2.png)

**Comment by RostyslavMatviyiv** [comment]
Here is the image you can test issue with 
![19983956_795798480594996_119329817416284633_o](https://user-images.githubusercontent.com/50489886/61696770-97ed4e00-ad3e-11e9-8086-9ef67abd4d7c.jpg)

**Comment by RostyslavMatviyiv** [comment]
So our client requested wrong behavior, when he tried to crop the image by TYPO3 Image Editor, he got wrongly cropped image on frontend however cropping area in editor was the same as previously. After investigation I understood that the problem related to wrong width and height in metadata record of that file, as I understood later image was resized on external editor like photoshop to the smaller size and the ones I saw in metadata record was original size of the image before resizing. And as much as you want you can resize image and upload by TYPO3 Filelist you will see the size of the original image. That size is saved to EXIF data in “ImageWidth” and “ImageHeight” fields, however the proper ones (after resizing) are saved to “ExifImageWidth”, “ExifImageHeight”.

TYPO3 built-in MetaDataExtractor works well during the indexing(uploading) the image and takes care of physical image size, but there is EXT:tika MetaDataExtractor which is connected as a service to the core Indexer (sysext/core/Classes/Resource/Index/Indexer.php, see screenshot 1) where it overrides the original metadata width and height properties (which are correct as I said) by the wrong ones which are taken from EXIF data from “ImageWidth” and “ImageHeight” fields in /typo3conf/ext/tika/Classes/Service/Extractor/MetaDataExtractor.php (see screenshot 2)

So what do you think? Can be just replacing (“ImageWidth” and “ImageHeight”) by (“ExifImageWidth”, “ExifImageHeight”) the fix in this case? (see screenshot 3)

![image](https://user-images.githubusercontent.com/50489886/61700450-6a57d300-ad45-11e9-8286-0c0a321ebb82.png)
![image](https://user-images.githubusercontent.com/50489886/61700462-6e83f080-ad45-11e9-855f-f338acb82915.png)
![image](https://user-images.githubusercontent.com/50489886/61700475-72b00e00-ad45-11e9-9fa8-9191d3f4923d.png)
Works well on my side with that images, but the question if it does not make any other issues

**Comment by josuavogel** [comment]
Hi, are there any updates concerning this bug?
